import { HomeViewer, SURFACES, MATERIALS, defaults, textureCanvas } from './home-viewer.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const styles=[['Modern',0,'Flat roof · clean lines'],['Contemporary',1,'Layered facade · warm finishes'],['Traditional',2,'Sloped roof · timeless details'],['Villa',3,'Generous terraces · elegant entry'],['Duplex',4,'Two levels · connected living'],['Farm House',5,'Natural materials · country character'],['Bungalow',6,'Relaxed proportions · sheltered porch'],['Minimalist',7,'Simple volumes · quiet palette'],['Custom',8,'Your own architectural direction']];
const themeData={ 'Modern White':['#F4F1E8','#B9BEC2','#7F5B3F','plaster'],'Luxury Stone':['#D6C8B4','#62564B','#3F3229','stone'],'Modern Black':['#BFC3C5','#353C40','#20282D','concrete'],'Tropical':['#EBDFCA','#8A6542','#466140','wood'],'Traditional':['#E8D6B8','#BB6949','#795334','brick'],'Minimal':['#F1F2EE','#BCBDB9','#242D31','plaster']};
const palette=['#FFFFFF','#F4F1E8','#D6C8B4','#BFC3C5','#424B50','#6B4A34','#C47935','#B95040','#E4BF45','#375975','#42704E'];
const features=['Exterior Style','Facade','Balcony','Roof','Windows','Doors','Entrance','Materials','Colors','Landscaping','Overall Appearance'];
let project,pid,viewer,bimData,state={versions:[],references:[]},config=defaults(),surface='exterior',selected=null,tab='gallery',renderMode='model',busy=false,counts={},search='',filter='',floorFilter='',favoritesOnly=false,favorites=[],dirty=false;
const blobs=new Map();
const url=p=>ProjectWorkspace.pageUrl(p,pid);
const endpoint=()=>`${resolveOhiseeApiBase()}/projects/${encodeURIComponent(pid)}/home-designs`;
async function api(path='',body,method='POST') {const r=await fetch(endpoint()+path,{method:body===undefined?'GET':method,headers:{Authorization:`Bearer ${TokenStore.get()}`,...(!(body instanceof FormData)&&body!==undefined?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(210000)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Could not complete this request. Please retry.');return data;}
function notice(message,error=false){const box=$('#hd-notice');box.className=error?'hd-error':'hd-message';box.textContent=message;box.hidden=!message;if(message)box.scrollIntoView({behavior:'smooth',block:'nearest'});}
async function task(message,fn){if(busy)return;busy=true;notice('');$('#hd-progress').hidden=false;$('#hd-progress-title').textContent=message;document.querySelectorAll('[data-mutation]').forEach(b=>b.disabled=true);try{await fn();}catch(e){notice(e.name==='TimeoutError'?'The request timed out. Refresh saved versions before retrying.':e.message,true);}finally{busy=false;$('#hd-progress').hidden=true;document.querySelectorAll('[data-mutation]').forEach(b=>b.disabled=false);}}
async function asset(path){if(!path)return null;if(blobs.has(path))return blobs.get(path);const r=await fetch(path,{headers:{Authorization:`Bearer ${TokenStore.get()}`}});if(!r.ok)throw new Error('The saved preview could not be loaded.');const u=URL.createObjectURL(await r.blob());blobs.set(path,u);return u;}
function art(i,large=false){const col=i%3,row=Math.floor(i/3),x=208+col*106,y=215+row*96;return `<svg viewBox="${x} ${y} 100 68" role="img" aria-label="House style reference"><image href="/images/home-design/style-reference.png" width="1536" height="1024"/></svg>`;}
function shell(){
$('#pw-content').innerHTML=`<div id="hd-notice" hidden role="alert"></div><div id="hd-progress" class="hd-progress" hidden role="status"><span class="hd-spinner"></span><div><strong id="hd-progress-title"></strong><p>Processing your project. Please keep this page open.</p></div></div><div id="hd-approved"></div>
<div class="hd-start"><button class="hd-choice" id="start-model"><span>⌂</span><span><b>Generate From Floor Plan</b><small>Use your saved layout and requirements</small></span></button><button class="hd-choice" id="start-upload"><span>↥</span><span><b>Upload Reference House</b><small>I need a house like this</small></span></button><button class="hd-choice" id="start-gallery"><span>▦</span><span><b>Explore House Designs</b><small>Find a style that feels like home</small></span></button></div>
<div class="hd-studio"><section class="hd-panel" id="hd-style-panel"></section><section class="hd-panel"><h2 class="hd-panel-title"><span class="hd-number">2</span> Your home, from your floor plan</h2><div class="hd-tabs" id="hd-preview-tabs"><button data-mode="model" class="active">Interactive 3D</button><button data-mode="render">Architectural Render</button><button id="compare-original">Before / After</button></div><div class="hd-view-shell" id="hd-view-shell"><div class="hd-view-label" id="hd-view-label">PROJECT MODEL · CONCEPT</div><div id="hd-viewer" class="hd-viewer"></div><img id="hd-render" class="hd-render" hidden alt="Generated architectural concept of this project"><div class="hd-view-tools" id="hd-model-tools">${[['iso','3D View'],['front','Front'],['rear','Rear'],['left','Left'],['right','Right'],['top','Top'],['rotate','360°'],['reset','Reset']].map(([k,l])=>`<button data-camera="${k}">${l}</button>`).join('')}<button id="hd-interior">Interior</button><button id="hd-fullscreen">Fullscreen</button></div></div><p class="hd-note" id="hd-preview-note">Drag to rotate · Scroll to zoom · Right-drag to pan. This model follows your saved floor plan.</p><div class="hd-link-row"><button class="hd-btn primary" data-mutation id="hd-render-button">Create Architectural Render →</button><button class="hd-btn" id="hd-download">Download PNG</button><a class="hd-btn" href="${url('project-floor-plan.html')}">← Floor Plan</a></div><p class="hd-note">Concept design. Professional review is required before construction.</p></section><section class="hd-panel hd-customize" id="hd-customize"></section></div>
<section class="hd-versions"><div class="hd-section-heading"><h2>3D Design Versions</h2><button class="hd-btn" id="hd-refresh">Refresh saved versions</button></div><div id="hd-version-grid" class="hd-version-grid"></div></section><div class="hd-footer"><button class="hd-btn primary" data-mutation id="hd-save">Save 3D Design</button><button class="hd-btn" data-mutation id="hd-review">Request Professional Review</button><button class="hd-btn" data-mutation id="hd-approve">Approve Selected Design</button><a class="hd-btn" href="${url('project-bim.html')}">Continue to BIM & Technical →</a><a class="hd-btn" href="${url('project-boq.html')}">Quantities / BOQ</a><a class="hd-btn" href="${url('project-cost.html')}">Cost Estimate</a></div><dialog id="hd-dialog" class="hd-dialog"></dialog>`;
$('#start-model').onclick=()=>generate(false);$('#start-upload').onclick=()=>{tab='upload';paintStyle();};$('#start-gallery').onclick=()=>{tab='gallery';paintStyle();};
$('#hd-render-button').onclick=()=>generate(true);$('#hd-save').onclick=()=>generate(false);$('#hd-refresh').onclick=()=>task('Loading saved designs',async()=>{state=await api();paintVersions();});
$('#hd-preview-tabs').onclick=e=>{const m=e.target.dataset.mode;if(m)setMode(m);};
$('#compare-original').onclick=()=>compareOriginal();
$('#hd-model-tools').onclick=e=>{const view=e.target.dataset.camera;if(view)viewer?.view(view);};
$('#hd-interior').onclick=()=>{if(!viewer)return;viewer.hiddenTypes.has('Roof')?viewer.hiddenTypes.delete('Roof'):viewer.hiddenTypes.add('Roof');viewer.loadModel(bimData.model);counts=viewer.applyConfiguration(config);};
$('#hd-fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('#hd-view-shell').requestFullscreen().catch(()=>notice('Fullscreen is unavailable in this browser.',true));
$('#hd-download').onclick=async()=>{try{if(renderMode==='render'){const v=state.versions.find(v=>v.id===selected);if(!v?.renderUrl)throw new Error('Create an architectural render first.');const a=document.createElement('a');a.href=await asset(v.renderUrl);a.download=`${pid}-V${v.version}-render.png`;a.click();}else if(viewer)viewer.exportScreenshot(`${pid}-3d-home.png`);else notice('Generate a floor plan first.',true);}catch(e){notice(e.message,true);}};
$('#hd-review').onclick=()=>versionAction('review');$('#hd-approve').onclick=()=>approveDialog();
paintStyle();paintCustomize();paintVersions();
}
function paintStyle(){
const el=$('#hd-style-panel');el.innerHTML=`<h2 class="hd-panel-title"><span class="hd-number">1</span> Choose a House Style</h2><div class="hd-tabs"><button data-tab="gallery" class="${tab==='gallery'?'active':''}">▦ Template Gallery</button><button data-tab="upload" class="${tab==='upload'?'active':''}">↥ Upload Image</button></div><div id="hd-style-content"></div>`;
el.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;paintStyle();});
if(tab==='upload'){paintUpload();return;}
$('#hd-style-content').innerHTML=`<div class="hd-fields"><input id="hd-search" class="hd-input" placeholder="Search house styles" value="${esc(search)}" aria-label="Search house styles"><button id="hd-favorites" class="hd-btn" aria-pressed="${favoritesOnly}">♡</button></div><div class="hd-fields"><select id="hd-style-filter" aria-label="Style filter"><option value="">All styles</option>${styles.map(s=>`<option ${filter===s[0]?'selected':''}>${s[0]}</option>`).join('')}</select><select id="hd-floor-filter" aria-label="Reference floor filter"><option value="">All floors</option><option value="1" ${floorFilter==='1'?'selected':''}>Single level</option><option value="2" ${floorFilter==='2'?'selected':''}>G + 1</option></select></div><div id="hd-gallery" class="hd-gallery"></div><div class="hd-selected"><b id="hd-selected-name">Selected: ${esc(config.style)}</b><p>Style inspiration only. Your project's dimensions, floors and rooms remain unchanged.</p><button class="hd-btn primary wide" id="hd-use-style" data-mutation>Use This Style →</button></div><p class="hd-note">House references supplied for this project.</p>`;
$('#hd-search').oninput=e=>{search=e.target.value;paintGallery();};$('#hd-style-filter').onchange=e=>{filter=e.target.value;paintGallery();};$('#hd-floor-filter').onchange=e=>{floorFilter=e.target.value;paintGallery();};$('#hd-favorites').onclick=()=>{favoritesOnly=!favoritesOnly;paintStyle();};$('#hd-use-style').onclick=()=>{applyStyle(config.style);notice(`${config.style} finishes applied to your model. Create an architectural render to explore the full facade style.`);};paintGallery();
}
function paintGallery(){const visible=styles.filter(s=>(!search||(s[0]+' '+s[2]).toLowerCase().includes(search.toLowerCase()))&&(!filter||filter===s[0])&&(!floorFilter||String(s[0]==='Farm House'?1:2)===floorFilter)&&(!favoritesOnly||favorites.includes(s[0])));$('#hd-gallery').innerHTML=visible.length?visible.map(([name,i,desc])=>`<article class="hd-style ${config.style===name?'selected':''}"><button data-style="${name}" aria-label="Select ${name}">${art(i)}<strong>${name}</strong><small>${name==='Farm House'?'Single level':'G + 1'} reference</small></button><div class="hd-style-actions"><button data-preview="${i}">Preview</button><button data-favorite="${name}" class="${favorites.includes(name)?'fav':''}" aria-label="Favorite ${name}">${favorites.includes(name)?'♥':'♡'}</button></div></article>`).join(''):'<p class="hd-note">No matching styles.</p>';$('#hd-gallery').querySelectorAll('[data-style]').forEach(b=>b.onclick=()=>{config.style=b.dataset.style;config.referenceId=null;dirty=true;paintStyle();});$('#hd-gallery').querySelectorAll('[data-favorite]').forEach(b=>b.onclick=()=>{const n=b.dataset.favorite;favorites=favorites.includes(n)?favorites.filter(x=>x!==n):[...favorites,n];localStorage.setItem(`ohisee_home_favorites_${pid}`,JSON.stringify(favorites));paintGallery();});$('#hd-gallery').querySelectorAll('[data-preview]').forEach(b=>b.onclick=()=>{const s=styles.find(s=>s[1]===Number(b.dataset.preview));dialog(`<h2>${s[0]}</h2>${art(s[1],true)}<p>${s[2]}. Style reference; your saved floor plan determines the actual dimensions.</p><button class="hd-btn primary" id="dialog-select">Select This Style</button>`);$('#dialog-select').onclick=()=>{config.style=s[0];dirty=true;$('#hd-dialog').close();paintStyle();};});}
function paintUpload(){const ref=state.references.find(r=>r.id===config.referenceId);$('#hd-style-content').innerHTML=`<h3>I need a house like this</h3><div class="hd-upload" id="hd-drop"><input type="file" id="hd-reference-file" accept="image/jpeg,image/png,image/webp" hidden>${ref?'<img id="hd-reference-preview" class="hd-ref-img" alt="Selected reference house">':'<p>Drag & drop a house image here</p>'}<button class="hd-btn" id="hd-browse">${ref?'Replace Image':'Upload House Image'}</button><p>JPG / PNG / WEBP · up to 10 MB</p>${ref?`<p>✓ ${esc(ref.name)}</p>`:''}</div><p class="hd-note">What do you like about this house?</p><div class="hd-checks">${features.map(f=>`<label><input type="checkbox" value="${f}" ${config.referenceFeatures.includes(f)?'checked':''}>${f}</label>`).join('')}</div><label class="hd-note" for="hd-instructions">Additional instructions</label><textarea id="hd-instructions" rows="4" maxlength="1500" placeholder="Similar facade, with my existing floor plan…">${esc(config.instructions)}</textarea><button class="hd-btn primary wide" id="hd-similar" data-mutation style="margin-top:12px">Generate Similar Design →</button><p class="hd-note">We use this image for appearance only. Your project layout remains the source of truth.</p>`;
if(ref)asset(ref.url).then(u=>{const img=$('#hd-reference-preview');if(img)img.src=u;}).catch(e=>notice(e.message,true));
$('#hd-browse').onclick=()=>$('#hd-reference-file').click();$('#hd-reference-file').onchange=e=>upload(e.target.files[0]);$('#hd-drop').ondragover=e=>e.preventDefault();$('#hd-drop').ondrop=e=>{e.preventDefault();upload(e.dataTransfer.files[0]);};$('#hd-instructions').oninput=e=>{config.instructions=e.target.value;dirty=true;};$('#hd-style-content').querySelectorAll('.hd-checks input').forEach(i=>i.onchange=()=>{config.referenceFeatures=[...document.querySelectorAll('.hd-checks input:checked')].map(x=>x.value);dirty=true;});$('#hd-similar').onclick=()=>{if(!config.referenceId)return notice('Upload a reference house first.',true);generate(true);};}
function upload(file){if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)return notice('Choose a JPG, PNG or WEBP image up to 10 MB.',true);task('Uploading your house reference',async()=>{const body=new FormData();body.append('image',file);state=await api('/reference',body);config.referenceId=state.references.at(-1).id;dirty=true;paintUpload();notice('Reference saved to this project. Choose the features you like, then Generate Similar Design.');});}
function paintCustomize(){const s=config.surfaces[surface];$('#hd-customize').innerHTML=`<h2 class="hd-panel-title"><span class="hd-number">3</span> Select Texture & Colours</h2><div><div class="hd-tabs">${['exterior','interior','roof','doors','windows','landscape'].map(k=>`<button data-surface="${k}" class="${surface===k?'active':''}">${({exterior:'Exterior',interior:'Interior',roof:'Roof',doors:'Doors',windows:'Windows',landscape:'Landscape'})[k]}</button>`).join('')}</div><select id="hd-surface" aria-label="Surface to customize">${Object.entries(SURFACES).map(([k,v])=>`<option value="${k}" ${surface===k?'selected':''}>${v}</option>`).join('')}</select><h3>Choose a material</h3><div class="hd-textures">${Object.entries(MATERIALS).map(([k,v])=>`<button class="hd-texture ${s.material===k?'active':''}" data-material="${k}"><img src="${textureCanvas(k,({brick:'#b98265',wood:'#9b7450',stone:'#9b9e96',granite:'#929792',concrete:'#aaaead'})[k]||'#e1ddd2').toDataURL()}" alt="${v} texture">${v}</button>`).join('')}</div><h3>Colour palette</h3><div class="hd-swatches">${palette.map(c=>`<button class="hd-swatch ${s.color===c?'active':''}" data-color="${c}" style="--swatch:${c}" aria-label="Color ${c}"></button>`).join('')}</div><div class="hd-color-row"><input type="color" id="hd-color-picker" value="${s.color}" aria-label="Custom color"><input class="hd-input" id="hd-color-text" value="${s.color}" aria-label="HEX or RGB color" placeholder="#F4F1E8 or rgb(244,241,232)"><button class="hd-btn" id="hd-apply-color">Apply</button></div><p class="hd-note" id="hd-surface-note"></p></div><div><div class="hd-divider"></div><h3>Preset themes</h3><div class="hd-themes">${Object.entries(themeData).map(([name,colors])=>`<button class="hd-btn" data-theme="${name}">${colors.slice(0,3).map(c=>`<i style="background:${c}"></i>`).join('')} ${name}</button>`).join('')}</div><button class="hd-btn wide" id="hd-preview-model" style="margin-top:15px">Preview on 3D</button><p class="hd-note">Materials update the interactive model immediately. Create a new render to update a saved image.</p></div>`;
$('#hd-customize').querySelectorAll('[data-surface]').forEach(b=>b.onclick=()=>{surface=b.dataset.surface;paintCustomize();});$('#hd-surface').onchange=e=>{surface=e.target.value;paintCustomize();};$('#hd-customize').querySelectorAll('[data-material]').forEach(b=>b.onclick=()=>changeSurface({material:b.dataset.material}));$('#hd-customize').querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>changeSurface({color:b.dataset.color}));$('#hd-color-picker').oninput=e=>{changeSurface({color:e.target.value},false);$('#hd-color-text').value=e.target.value;};$('#hd-apply-color').onclick=()=>{let value=$('#hd-color-text').value.trim();const rgb=/^rgb\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*\)$/i.exec(value);if(rgb&&rgb.slice(1).every(v=>+v<=255))value='#'+rgb.slice(1).map(v=>(+v).toString(16).padStart(2,'0')).join('');if(!/^#[0-9a-f]{6}$/i.test(value))return notice('Enter a six-digit HEX value or rgb(0–255, 0–255, 0–255).',true);changeSurface({color:value});};$('#hd-customize').querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>applyTheme(b.dataset.theme));$('#hd-preview-model').onclick=()=>setMode('model');surfaceNote();}
function surfaceNote(){const el=$('#hd-surface-note');if(el)el.textContent=counts[surface]?`${counts[surface]} model elements use this finish.`:'This surface is not present in the current model. Its finish is saved for architectural rendering.';}
function changeSurface(patch,paint=true){Object.assign(config.surfaces[surface],patch);dirty=true;if(viewer)counts=viewer.applyConfiguration(config);if(paint)paintCustomize();if(renderMode==='render')notice('Finish changed. Preview it on the interactive model or create a new architectural render.');}
function applyTheme(name){const [primary,secondary,accent,material]=themeData[name];config.surfaces.exterior={color:primary,material};config.surfaces.secondary={color:secondary,material};config.surfaces.accent={color:accent,material:'wood'};dirty=true;if(viewer)counts=viewer.applyConfiguration(config);paintCustomize();setMode('model');}
function applyStyle(name){applyTheme(name==='Traditional'?'Traditional':name==='Farm House'?'Tropical':name==='Minimalist'?'Minimal':'Modern White');}
function mountModel(){viewer?.dispose();viewer=null;const c=$('#hd-viewer');c.innerHTML='';if(!bimData?.model){c.innerHTML=`<div class="hd-empty">${art(0)}<h2>Your floor plan. Your future home.</h2><p>Generate the project's floor plan to unlock your interactive 3D model.</p><a class="hd-btn primary" href="${url('project-floor-plan.html')}">Open Floor Plan →</a><small class="hd-muted">Above: style inspiration, not a generated project.</small></div>`;return;}try{viewer=new HomeViewer(c);viewer.loadModel(bimData.model);counts=viewer.applyConfiguration(config);surfaceNote();}catch(e){c.innerHTML='<div class="hd-empty"><h2>3D preview unavailable</h2><p>Enable WebGL in your browser to view the interactive model. Saved renders and versions remain available.</p></div>';}}
async function setMode(mode){try{if(mode==='render'){const v=state.versions.find(v=>v.id===selected);if(!v?.renderUrl)return notice('Create an architectural render to see it here.',true);$('#hd-render').src=await asset(v.renderUrl);}renderMode=mode;$('#hd-viewer').hidden=mode!=='model';$('#hd-render').hidden=mode!=='render';$('#hd-model-tools').hidden=mode!=='model';$('#hd-view-label').textContent=mode==='model'?'PROJECT MODEL · INTERACTIVE 3D':'ARCHITECTURAL RENDER · CONCEPT IMAGE';$('#hd-preview-note').textContent=mode==='model'?'Drag to rotate · Scroll to zoom · Right-drag to pan. Based on your saved floor plan.':'Generated concept image. Model geometry and dimensions remain authoritative.';$('#hd-preview-tabs').querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));viewer?.onResize();}catch(e){notice(e.message,true);}}
async function generate(render=false,sourceId=null){await task(render?'Creating your architectural render…':'Saving your 3D home…',async()=>{if(!bimData?.model){notice('Generate a floor plan first, then return to create your 3D home.',true);return;}if(render&&!state.renderAvailable)throw new Error('Architectural rendering is not connected. You can still customize and save the interactive model.');const scene=viewer?.snapshot();state=await api('',{configuration:config,render,sourceId:sourceId||selected||undefined,scene,name:config.style});selected=state.selectedId;dirty=false;paintVersions();if(render)await setMode('render');notice(render?'Your architectural render is ready and saved as a new version.':'3D design saved as a new version.');});}
async function loadVersion(id){await task('Loading saved design…',async()=>{const v=state.versions.find(v=>v.id===id);if(!v)throw new Error('Design not found.');const r=await fetch(v.modelUrl,{headers:{Authorization:`Bearer ${TokenStore.get()}`}});if(!r.ok)throw new Error('Saved model could not be loaded.');bimData=await r.json();config={...defaults(),...structuredClone(v.configuration),surfaces:{...defaults().surfaces,...structuredClone(v.configuration.surfaces)}};selected=id;dirty=false;mountModel();paintStyle();paintCustomize();paintVersions();await setMode(v.renderUrl?'render':'model');});}
function paintVersions(){const versions=state.versions.filter(v=>v.status!=='Archived');$('#hd-version-grid').innerHTML=versions.length?versions.map(v=>`<article class="hd-version ${selected===v.id?'selected':''}"><img data-version-image="${v.id}" alt="Preview of ${esc(v.name)}" ${v.renderUrl||v.previewUrl?'':'hidden'}><div class="hd-version-content"><h3>V${v.version} · ${esc(v.name)}</h3><p>${esc(v.status)} · ${new Date(v.createdAt).toLocaleDateString()}${v.status==='Approved'?' · Locked':''}</p><div class="hd-version-actions"><button class="hd-btn" data-load="${v.id}">View</button><button class="hd-btn" data-compare="${v.id}">Compare</button><button class="hd-btn" data-restore="${v.id}" data-mutation>Restore / Duplicate</button>${v.status!=='Approved'?`<button class="hd-btn" data-archive="${v.id}" data-mutation>Archive</button>`:''}</div></div></article>`).join(''):'<p class="hd-note">No saved designs yet. Customize the model, then save your first version.</p>';
for(const v of versions){if(v.renderUrl||v.previewUrl)asset(v.renderUrl||v.previewUrl).then(src=>{const img=document.querySelector(`[data-version-image="${v.id}"]`);if(img)img.src=src;}).catch(()=>{});}
$('#hd-version-grid').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>loadVersion(b.dataset.load));$('#hd-version-grid').querySelectorAll('[data-restore]').forEach(b=>b.onclick=async()=>{await loadVersion(b.dataset.restore);if(selected===b.dataset.restore)await generate(false,b.dataset.restore);});$('#hd-version-grid').querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>compareVersions(b.dataset.compare));$('#hd-version-grid').querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{dialog('<h2>Archive this draft?</h2><p>It will be removed from the active version gallery. Approved designs cannot be archived.</p><button class="hd-btn primary" id="hd-confirm-archive">Archive draft</button>');$('#hd-confirm-archive').onclick=()=>{$('#hd-dialog').close();versionAction('archive',b.dataset.archive);};});
const approved=state.versions.find(v=>v.id===state.approvedId);$('#hd-approved').innerHTML=approved?`<div class="hd-approval">✓ Customer-approved design · V${approved.version} · ${new Date(approved.approvedAt).toLocaleDateString()} — professional review is still required before construction.</div>`:'';
}
function dialog(html){const d=$('#hd-dialog');d.innerHTML=html+'<div><button class="hd-btn" id="hd-dialog-close">Close</button></div>';$('#hd-dialog-close').onclick=()=>d.close();d.showModal();}
async function compareOriginal(){if(!viewer)return notice('Load a 3D model first.',true);const after=viewer.snapshot();viewer.applyConfiguration(defaults());const before=viewer.snapshot();viewer.applyConfiguration(config);dialog(`<h2>Before / After · same floor plan</h2><div class="hd-compare"><div><p>Original finishes</p><img src="${before}" alt="Original model finishes"></div><div><p>Your customized finishes</p><img src="${after}" alt="Customized model finishes"></div></div>`);}
async function compareVersions(id){try{const a=state.versions.find(v=>v.id===selected),b=state.versions.find(v=>v.id===id);if(!a||!b)return notice('View a version first, then compare another.',true);const imgs=await Promise.all([a,b].map(v=>asset(v.renderUrl||v.previewUrl)));dialog(`<h2>Compare saved versions</h2><div class="hd-compare">${[a,b].map((v,i)=>`<div><p>V${v.version} · ${esc(v.name)} · ${esc(v.status)}</p>${imgs[i]?`<img src="${imgs[i]}" alt="Version ${v.version}">`:'<p>No saved preview</p>'}<p>${esc(v.configuration.style)} · ${esc(v.configuration.surfaces.exterior?.material||'')}</p></div>`).join('')}</div>`);}catch(e){notice(e.message,true);}}
function approveDialog(){const v=state.versions.find(v=>v.id===selected);if(!v)return notice('Save and select a design first.',true);if(dirty)return notice('Save your latest changes as a new version before approving.',true);dialog(`<h2>Approve V${v.version}?</h2><p>This records your design preference and locks this version. It does not certify structural safety or authorize construction. Professional review is still required.</p><button class="hd-btn primary" id="hd-confirm-approve">Approve This Design</button>`);$('#hd-confirm-approve').onclick=()=>{$('#hd-dialog').close();versionAction('approve');};}
async function versionAction(action,id=selected){if(!id)return notice('Save and select a design first.',true);await task('Saving design status…',async()=>{state=await api(`/${id}/${action}`,{});paintVersions();notice(action==='review'?'Professional review requested and recorded on this project.':action==='approve'?'Selected version approved and locked.':'Version archived.');});}
async function init(){pid=ProjectWorkspace.getProjectId();if(!pid){$('#pw-content').innerHTML='<div class="hd-error">Open this page from a project’s Floor Plan.</div>';return;}if(!ProjectWorkspace.requireAuth(pid))return;try{project=await ProjectWorkspace.loadProject(pid);if(!project)throw new Error('Project not found.');ProjectWorkspace.renderNav('3d',pid);$('#hd-header-project').textContent=project.project_name||pid;$('#pw-topbar').innerHTML=`<div class="hd-heading"><div><h1>3D HOME DESIGN</h1><p>Create your home using your floor plan and a style you love.</p></div><div class="hd-meta"><span>Project: ${esc(pid)}</span><span>${esc(project.project_type||'')}</span><span>${esc(project.built_up_area||'')}</span></div></div>`;state=await api();try{favorites=JSON.parse(localStorage.getItem(`ohisee_home_favorites_${pid}`)||'[]');}catch{}try{bimData=(await BimAPI.getModel(pid)).data;}catch{bimData=null;}shell();mountModel();if(state.selectedId)await loadVersion(state.selectedId);}catch(e){$('#pw-content').innerHTML=`<div class="hd-error">${esc(e.message)}</div><a class="hd-btn" href="${url('project-floor-plan.html')}">Return to Floor Plan</a>`;}}
window.addEventListener('pagehide',()=>{viewer?.dispose();for(const u of blobs.values())URL.revokeObjectURL(u);});
init();