apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohisee-api
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohisee-frontend
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ohisee-design3d-worker
spec:
  replicas: 1
