'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {app,records,reset,token}=require('./home-design-fixture');
const service=require('../src/services/homeDesign');
let server,base;const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a5S8AAAAASUVORK5CYII=','base64');
test.before(async()=>{server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port+'/api/projects/P1/home-designs';});
test.after(()=>new Promise(r=>server.close(r)));test.beforeEach(reset);
async function req(path='',body,user='c1'){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{...(user?{Authorization:'Bearer '+token(user)}:{}),...(!(body instanceof FormData)?{'Content-Type':'application/json'}:{})},...(body!==undefined?{body:body instanceof FormData?body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};}
const config={style:'Modern',surfaces:{exterior:{color:'#F4F1E8',material:'stone'},roof:{color:'#333333',material:'concrete'}}};
const create=()=>req('',{configuration:config,scene:'data:image/png;base64,'+png.toString('base64')});
test('design snapshots persist on the existing project, with exact floor plan and private assets',async()=>{const r=await create();assert.equal(r.status,201);assert.equal(records.projects.length,1);const v=r.data.versions[0];assert.equal(v.floorPlanVersion,'floor-plan-v1');assert.equal(v.configuration.surfaces.exterior.material,'stone');assert.equal(v.modelKey,undefined);const model=await fetch('http://127.0.0.1:'+server.address().port+v.modelUrl,{headers:{Authorization:'Bearer '+token('c1')}});assert.equal(model.status,200);assert.ok((await model.json()).model.elements.length>10);assert.equal((await req()).data.versions.length,1);});
test('approved designs are immutable, duplication preserves original approval',async()=>{let r=await create();const id=r.data.selectedId;r=await req('/'+id+'/approve',{});assert.equal(r.data.versions[0].status,'Approved');assert.equal((await req('/'+id+'/archive',{})).status,409);assert.equal((await req('/'+id+'/review',{})).status,409);r=await req('',{configuration:{...config,style:'Traditional'},sourceId:id});assert.equal(r.status,201);assert.equal(r.data.versions[0].status,'Approved');assert.equal(r.data.versions[1].status,'Draft');assert.equal(r.data.versions[1].version,2);assert.equal(r.data.versions[1].sourceId,id);});
test('reference upload validates content and remains project-owned',async()=>{const f=new FormData();f.append('image',new Blob([png],{type:'image/png'}),'reference.png');let r=await req('/reference',f);assert.equal(r.status,201);const ref=r.data.references[0];assert.equal(ref.key,undefined);r=await req('',{configuration:{...config,referenceId:ref.id}});assert.equal(r.data.versions[0].referenceImageId,ref.id);const bad=new FormData();bad.append('image',new Blob(['<script>bad</script>'],{type:'image/png'}),'bad.png');assert.equal((await req('/reference',bad)).status,400);});
test('other customers and unauthenticated callers cannot read designs or private assets',async()=>{const r=await create();assert.equal((await req('',undefined,'c2')).status,404);assert.equal((await req('',undefined,null)).status,401);const a=await fetch('http://127.0.0.1:'+server.address().port+r.data.versions[0].modelUrl,{headers:{Authorization:'Bearer '+token('c2')}});assert.equal(a.status,404);});
test('invalid colors and foreign references do not create versions',async()=>{assert.equal((await req('',{configuration:{surfaces:{exterior:{color:'javascript:1',material:'stone'}}}})).status,400);assert.equal((await req('',{configuration:{...config,referenceId:'00000000-0000-4000-8000-000000000000'}})).status,404);assert.equal((await req()).data.versions.length,0);});
test('failed image rendering does not save a misleading generated version',async()=>{const old=process.env.OPENAI_API_KEY;delete process.env.OPENAI_API_KEY;try{const r=await req('',{configuration:config,render:true,scene:'data:image/png;base64,'+png.toString('base64')});assert.equal(r.status,503);assert.equal((await req()).data.versions.length,0);}finally{if(old)process.env.OPENAI_API_KEY=old;}});
test('concurrent updates cannot overwrite project context',async()=>{const p=await service.owned('P1','c1');records.projects[0].updated_at='changed';await assert.rejects(service.create(p,'c1',{configuration:config}),e=>e.status===409);assert.equal(records.projects[0].construction_context.homeDesign,undefined);});