'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),s=require('../src/services/roadmapService');
function context(floors=1){const data={project:{floors},stage:'in_execution'};const act=(operation,extra={},contractor=true,at='2026-09-17T12:00:00.000Z')=>s.apply(data,{operation,...extra},contractor,contractor?'builder':'client',at);return {data,act};}
function agreed(c){c.act('grade',{grade:'Standard',specification:'Structural S1 and architectural A2; selected finish schedule F1.'});c.act('approve_grade',{},false);}
function prep(c,id){c.act('draw',{stage_id:id,note:'Approved drawing S1'});c.act('check',{stage_id:id,inspector:'Site engineer',note:'Inspection evidence reference CHECK-1'});c.act('approve',{stage_id:id},false);}
function finish(c,id){prep(c,id);c.act('execute',{stage_id:id},true,'2026-09-01T12:00:00.000Z');c.act('measure',{stage_id:id,note:'Executed quantity',unit:'item',quantity:1});const spec=s.catalog.stages.find(x=>x.id===c.data.roadmap.stages.find(x=>x.id===id).catalog_id);if(spec.curing!=='None')c.act('curing',{stage_id:id,start:'2026-09-01',end:'2026-09-08',note:'Engineer specified period and observations recorded'});c.act('record',{stage_id:id,note:'Engineer completion clearance and testing record'});}
test('catalog contains all 20 stages and 5 grades without automatically setting structural sizes',()=>{assert.equal(s.catalog.stages.length,20);assert.equal(s.catalog.grades.length,5);assert.equal(s.initial({floors:2}).stages.length,23);const c=context();agreed(c);assert.equal(c.data.project.slab_thickness,undefined);});
test('roles, agreement and ordered inspections gate execution',()=>{const c=context();assert.throws(()=>c.act('grade',{grade:'Standard',specification:'a'},false),/Contractor/);agreed(c);assert.throws(()=>c.act('execute',{stage_id:'design'}),/Draw, check/);c.act('draw',{stage_id:'design',note:'A1'});assert.throws(()=>c.act('approve',{stage_id:'design'},false),/Inspection/);c.act('check',{stage_id:'design',note:'Checked',inspector:'Engineer'});assert.throws(()=>c.act('approve',{stage_id:'design'}),/Customer/);c.act('approve',{stage_id:'design'},false);c.act('execute',{stage_id:'design'});assert.throws(()=>c.act('grade',{grade:'Luxury',specification:'new'}),/before site work/);});
test('measurements calculate volume on server; curing cannot be completed early',()=>{const c=context();agreed(c);for(const id of ['design','survey','preparation','excavation'])finish(c,id);prep(c,'pcc');c.act('execute',{stage_id:'pcc'});c.act('measure',{stage_id:'pcc',unit:'m3',length:4,width:2,depth:0.1,count:2,quantity:999,note:'PCC base'});const pcc=c.data.roadmap.stages.find(x=>x.id==='pcc');assert.equal(pcc.measurements[0].quantity,1.6);c.act('curing',{stage_id:'pcc',start:'2026-09-17',end:'2026-09-24',note:'Cure per site engineer'});assert.throws(()=>c.act('record',{stage_id:'pcc',note:'done'}),/has not ended/);prep(c,'footing_steel');assert.throws(()=>c.act('execute',{stage_id:'footing_steel'}),/curing\/testing/);});
test('complete roadmap, rectify snag, submit records then customer handover approval',()=>{const c=context();agreed(c);for(const stage of c.data.roadmap.stages)finish(c,stage.id);c.act('snag',{description:'Kitchen tap leak',responsible:'Plumber',due:'2026-09-20'},false);assert.throws(()=>c.act('handover',{documents:'reports'}),/Close all snags/);const id=c.data.roadmap.snags[0].id;c.act('resolve_snag',{snag_id:id,note:'Replaced seal and pressure tested'});c.act('close_snag',{snag_id:id},false);c.act('handover',{documents:'Test reports T1; warranties W1; manuals M1; keys K1; as-builts A3.'});assert.throws(()=>c.act('approve_handover'),/Customer/);c.act('approve_handover',{},false);assert.ok(c.data.roadmap.handover.approved_at);assert.throws(()=>c.act('snag',{}),/already signed off/);});
test('second-floor columns require first-floor slab completion',()=>{const c=context(2);agreed(c);for(const id of ['design','survey','preparation','excavation','pcc','footing_steel','footing_concrete','plinth'])finish(c,id);finish(c,'columns_0');prep(c,'columns_1');assert.throws(()=>c.act('execute',{stage_id:'columns_1'}),/preceding/);finish(c,'slab_0');c.act('execute',{stage_id:'columns_1'});assert.equal(c.data.roadmap.stages.find(x=>x.id==='columns_1').status,'executed');});
