apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ohisee-ingress
spec:
  tls:
    - hosts:
        - staging.ohisee.com
        - api.staging.ohisee.com
      secretName: ohisee-staging-tls
  rules:
    - host: staging.ohisee.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ohisee-frontend
                port:
                  number: 80
    - host: api.staging.ohisee.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ohisee-api
                port:
                  number: 3001
