/* Shared real-generation interface used by New Home and the existing visualizer. */
(() => {
'use strict';
const newHome=location.pathname.endsWith('intent-engine.html')&&new URLSearchParams(location.search).get('intent')==='NEW_HOME';
const visualizer=location.pathname.endsWith('visualizer-3d.html');
if(!newHome&&!visualizer)return;
const base=window.OHISEE_API_BASE||(['localhost','127.0.0.1'].includes(location.hostname)?`${location.protocol}//${location.hostname}:3001/api`:'/api');
const token=()=>localStorage.getItem('ohisee_jwt')||localStorage.getItem('ohisee_token')||sessionStorage.getItem('ohisee_token');
const root=document.createElement('section');root.className='oh3d container';root.id='construction-design';
root.innerHTML=`<div class="oh3d-card"><h2>${newHome?'CREATE YOUR NEW HOME':'CREATE YOUR 3D DESIGN'}</h2><p>Describe your home in your own words. We’ll create a construction specification, build the model and render your design.</p>
<div class="oh3d-actions" role="group" aria-label="Design input"><button type="button" id="oh3d-text" aria-pressed="true">Create with AI</button><button type="button" id="oh3d-upload-tab" aria-pressed="false">Upload a floor plan</button></div>
<form id="oh3d-form"><div id="oh3d-upload-wrap" hidden><label for="oh3d-upload">Floor plan · PNG, JPG or PDF · up to 6 MB</label><input id="oh3d-upload" type="file" accept=".png,.jpg,.jpeg,.pdf"><p class="oh3d-small">Use a readable, dimensioned drawing. If measurements are unclear, we’ll ask you rather than invent them.</p></div>
<label for="oh3d-prompt">What do you want to build?</label><textarea id="oh3d-prompt" required maxlength="8000" placeholder="I want a modern 2-floor home with 4 bedrooms, a large living room, a balcony and a garden."></textarea>
<div class="oh3d-grid"><div><label for="oh3d-location">Location</label><input id="oh3d-location" placeholder="Coimbatore" maxlength="160"></div><div><label for="oh3d-style">Style</label><select id="oh3d-style"><option value="">Use my description</option><option>Modern</option><option>Contemporary</option><option>Traditional</option><option>Luxury</option></select></div><div><label for="oh3d-budget">Budget in ₹ · optional</label><input id="oh3d-budget" type="number" min="1"></div><div><label for="oh3d-width">Plot width in feet · optional</label><input id="oh3d-width" type="number" min="15" max="300" step="any"></div><div><label for="oh3d-depth">Plot depth in feet · optional</label><input id="oh3d-depth" type="number" min="15" max="300" step="any"></div></div>
<label class="inline"><input id="oh3d-interiors" type="checkbox"> Include living room, kitchen and bedroom renders (takes longer)</label><div class="oh3d-actions"><button class="primary" id="oh3d-generate">GENERATE 3D DESIGN</button><button type="button" id="oh3d-projects-button">My saved designs</button></div></form>
<p id="oh3d-error" class="oh3d-error" role="alert" hidden></p><p id="oh3d-login" hidden><a class="oh3d-link" href="login.html">Sign in to save and generate your design</a></p><div id="oh3d-saved" hidden></div></div>
<div class="oh3d-card" id="oh3d-job" hidden aria-live="polite"><h2>CREATING YOUR 3D DESIGN</h2><p id="oh3d-message"></p><progress id="oh3d-progress" max="100" value="0"></progress><ol class="oh3d-steps"><li>Understanding requirements</li><li>Building architecture</li><li>Applying materials</li><li>Lighting</li><li>Rendering</li></ol><p class="oh3d-small" id="oh3d-jobid"></p><div class="oh3d-actions"><button id="oh3d-resume" type="button" hidden>Check status again</button><button id="oh3d-retry" type="button" hidden>Retry Render</button></div></div>
<div class="oh3d-card" id="oh3d-result" hidden><h2>YOUR AI GENERATED HOME</h2><p class="oh3d-meta" id="oh3d-meta"></p><div class="oh3d-actions" id="oh3d-tabs" role="group" aria-label="Render views"></div><img class="oh3d-render" id="oh3d-image" alt="Your generated home design"><div class="oh3d-actions"><button id="oh3d-download" type="button">Download render</button><button id="oh3d-blend" type="button">Download Blender project</button><button id="oh3d-open-model" type="button" hidden>OPEN INTERACTIVE 3D</button></div><div class="oh3d-viewer" id="oh3d-viewer" hidden></div><details><summary>Design specification and assumptions</summary><div id="oh3d-assumptions"></div><pre id="oh3d-spec" style="white-space:pre-wrap;overflow-wrap:anywhere"></pre></details><h3>MODIFY DESIGN</h3><form id="oh3d-modify-form"><label for="oh3d-modify">Tell us what to change</label><textarea id="oh3d-modify" required maxlength="8000" placeholder="Make the living room larger and change the exterior to white marble."></textarea><div class="oh3d-actions"><button class="primary" id="oh3d-update">UPDATE DESIGN</button></div></form><details id="oh3d-history"><summary>Version history</summary><div class="oh3d-versions" id="oh3d-versions"></div></details></div>`;
const anchor=document.querySelector(newHome?'.intent-body':'.viz-hero');if(newHome)anchor.before(root);else anchor.after(root);
const $=id=>root.querySelector('#oh3d-'+id);
let projectId=null,currentVersion=0,currentJob=null,lastVersionId=null,busy=false,pollTimer=null,renderLinks={},activeRender=null,blobUrl=null,viewDispose=null;
const draftKey='ohisee_3d_draft';try{const draft=JSON.parse(sessionStorage.getItem(draftKey)||'null');if(draft)$('prompt').value=draft.prompt||'';}catch{}
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function lock(value){busy=value;for(const id of ['generate','update'])$(id).disabled=value;}
async function api(path,body){const t=token();if(!t){$('login').hidden=false;sessionStorage.setItem(draftKey,JSON.stringify({prompt:$('prompt').value}));throw Error('Sign in to create and manage your designs.');}const r=await fetch(base+'/3d'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+t,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw Error(data.error||'Unable to connect to the 3D service.');return data;}
function assetUrl(url){return url.startsWith('/api/')?base.replace(/\/api$/,'')+url:url;}
async function asset(url){const resolved=assetUrl(url);const local=new URL(resolved,location.href).origin===new URL(base,location.href).origin;const r=await fetch(resolved,{headers:local?{Authorization:'Bearer '+token()}: {}});if(!r.ok)throw Error('The saved file could not be loaded. Refresh the design and try again.');return r.blob();}
async function showRender(kind){error('');activeRender=kind;for(const b of $('tabs').children)b.setAttribute('aria-pressed',String(b.dataset.kind===kind));const expected=kind;try{const b=await asset(renderLinks[kind]);if(activeRender!==expected)return;if(blobUrl)URL.revokeObjectURL(blobUrl);blobUrl=URL.createObjectURL(b);$('image').src=blobUrl;}catch(e){error(e.message);}}
async function download(url,name){try{const b=await asset(url),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}catch(e){error(e.message);}}
async function display(data){
 renderLinks=data.renders||{};$('result').hidden=!renderLinks.exterior;if(!renderLinks.exterior)return;
 if(viewDispose){viewDispose();viewDispose=null;}$('viewer').hidden=true;
 const s=data.specification;currentVersion=data.version||currentVersion;lastVersionId=data.versionId;
 $('meta').textContent=s?`${s.building.style} · ${s.building.floors} floor${s.building.floors>1?'s':''} · ${s.location} · ${s.building.builtUpArea.toLocaleString()} sq.ft built-up · ${s.rooms.bedrooms} bedrooms · Version ${currentVersion}`:`Version ${currentVersion}`;
 $('spec').textContent=JSON.stringify(s,null,2);$('assumptions').textContent=(s?.assumptions||[]).join(' ');$('tabs').replaceChildren();
 for(const [kind,label] of Object.entries({exterior:'Exterior',livingRoom:'Living room',kitchen:'Kitchen / dining',masterBedroom:'Master bedroom'})){if(!renderLinks[kind])continue;const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.kind=kind;b.onclick=()=>showRender(kind);$('tabs').append(b);}
 $('blend').onclick=()=>download(data.project,'ohisee-home.blend');$('blend').disabled=!data.project;
 $('download').onclick=()=>download(renderLinks[activeRender],activeRender+'.png');
 $('open-model').hidden=!data.model;$('open-model').onclick=async()=>{try{$('open-model').disabled=true;const blob=await asset(data.model);const {openViewer}=await window.loadDesign3DViewer();$('viewer').hidden=false;viewDispose=await openViewer($('viewer'),await blob.arrayBuffer());}catch(e){error('Interactive viewer unavailable: '+e.message);}finally{$('open-model').disabled=false;}};
 await showRender('exterior');
}
function status(data){$('job').hidden=false;$('message').textContent=data.message||(data.status==='queued'?'Your project is saved and queued. It will continue when the 3D engine is available.':'Creating your design…');$('progress').value=data.progress||0;$('jobid').textContent=`${data.jobId} · ${data.status}`;const stages=['processing','building','materials','lighting','rendering','completed'];const index=stages.indexOf(data.status);[...root.querySelectorAll('.oh3d-steps li')].forEach((li,i)=>li.classList.toggle('done',i<=index));}
async function poll(){
 clearTimeout(pollTimer);if(!currentJob)return;
 try{const data=await api('/jobs/'+encodeURIComponent(currentJob));status(data);lastVersionId=data.versionId;$('resume').hidden=true;
 if(data.status==='completed'){lock(false);await display(data);await versions();return;}
 if(data.status==='failed'){lock(false);$('retry').hidden=!data.project||data.code!=='RENDER_FAILED';error(data.message||'Generation failed. Your project has been retained.');if(data.renders?.exterior)await display(data);return;}
 pollTimer=setTimeout(poll,4000);
 }catch(e){error(e.message);$('resume').hidden=false;lock(false);}
}
function jobStarted(data){currentJob=data.jobId;projectId=data.projectId;$('retry').hidden=true;lock(true);status(data);const url=new URL(location.href);url.searchParams.set('design',projectId);history.replaceState(null,'',url);sessionStorage.setItem('ohisee_3d_project',projectId);poll();}
async function upload(){const f=$('upload').files[0];if(!f)return null;if(f.size>6*1024*1024)throw Error('Choose a floor plan under 6 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(f);});return {name:f.name,data};}
$('form').onsubmit=async e=>{e.preventDefault();if(busy)return;error('');lock(true);try{
 const file=$('upload-wrap').hidden?null:await upload();if(!$('upload-wrap').hidden&&!file)throw Error('Choose your floor-plan file.');
 const created=projectId && currentVersion===0 ? {projectId} : await api('/projects',{prompt:$('prompt').value,location:$('location').value,style:$('style').value,budget:$('budget').value,plotWidth:$('width').value,plotDepth:$('depth').value,upload:file});projectId=created.projectId;currentVersion=0;
 const url=new URL(location.href);url.searchParams.set('design',projectId);history.replaceState(null,'',url);
 jobStarted(await api('/projects/'+projectId+'/generate',{prompt:$('prompt').value,currentVersion:0,requestId:crypto.randomUUID(),render:{interiors:$('interiors').checked}}));
 }catch(e){lock(false);error(e.message);}};
$('modify-form').onsubmit=async e=>{e.preventDefault();if(busy)return;lock(true);error('');try{jobStarted(await api('/projects/'+projectId+'/modify',{prompt:$('modify').value,currentVersion,requestId:crypto.randomUUID(),render:{interiors:$('interiors').checked}}));}catch(e){lock(false);error(e.message);}};
$('retry').onclick=async()=>{lock(true);try{jobStarted(await api('/projects/'+projectId+'/retry-render',{versionId:lastVersionId,currentVersion,requestId:crypto.randomUUID(),render:{interiors:$('interiors').checked}}));}catch(e){lock(false);error(e.message);}};
$('resume').onclick=poll;
$('text').onclick=()=>{$('upload-wrap').hidden=true;$('text').setAttribute('aria-pressed','true');$('upload-tab').setAttribute('aria-pressed','false');};
$('upload-tab').onclick=()=>{$('upload-wrap').hidden=false;$('text').setAttribute('aria-pressed','false');$('upload-tab').setAttribute('aria-pressed','true');};
async function versions(){if(!projectId)return;const d=await api('/projects/'+projectId+'/versions');$('versions').replaceChildren();for(const v of d.versions){const b=document.createElement('button');b.type='button';b.textContent=`Version ${v.version} · ${v.status}${v.version===d.currentVersion?' · current':''}`;b.disabled=v.status!=='completed'||busy;b.onclick=async()=>{try{await api(`/projects/${projectId}/versions/${v.versionId}/restore`,{currentVersion});currentVersion=v.version;await display(v);await versions();}catch(e){error(e.message);}};$('versions').append(b);}}
$('history').ontoggle=()=>{if($('history').open)versions().catch(e=>error(e.message));};
async function load(id){clearTimeout(pollTimer);projectId=id;const d=await api('/projects/'+id);currentVersion=d.currentVersion;$('prompt').value=d.prompt||'';if(d.result)await display(d.result);if(d.jobId){currentJob=d.jobId;const active=!['completed','failed'].includes(d.status);lock(active);if(active)await poll();else if(d.status==='failed')await poll();}else{error('This project is saved but has no generation job. Submit your requirements to start a new design.');}await versions();}
$('projects-button').onclick=async()=>{try{const d=await api('/projects');$('saved').hidden=false;$('saved').replaceChildren();if(!d.projects.length)$('saved').textContent='No saved designs yet.';for(const p of d.projects){const b=document.createElement('button');b.type='button';b.textContent=p.prompt.slice(0,80)+' · '+p.status;b.onclick=()=>load(p.projectId).catch(e=>error(e.message));$('saved').append(b);}}catch(e){error(e.message);}};
const saved=new URLSearchParams(location.search).get('design');if(saved)load(saved).catch(e=>error(e.message));
window.addEventListener('pagehide',()=>{clearTimeout(pollTimer);if(blobUrl)URL.revokeObjectURL(blobUrl);viewDispose?.();});
})();
