(function(root){
'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(name,label,type='text',extra='')=>`<label>${label}<input name="${name}" type="${type}" ${extra} required></label>`;
const note=label=>`<label>${label}<textarea name="note" required maxlength="5000"></textarea></label>`;
function form(op,content,stage=''){return `<form data-roadmap-action="${op}" data-stage="${stage}" class="mp-card mp-roadmap-form">${content}<button type="submit">${({grade:'Submit specification',approve_grade:'Approve specification',draw:'Save drawing revision',check:'Record inspection',approve:'Approve checked stage',execute:'Record execution',measure:'Add measurement',curing:'Add curing / test record',record:'Complete stage record',snag:'Report snag',resolve_snag:'Submit correction',close_snag:'Approve correction',handover:'Submit handover',approve_handover:'Sign off handover'})[op]}</button></form>`;}
async function render(el,j,contractor,action){
 const c=await MarketplaceUI.api('/roadmap-catalog'),r=j.data.roadmap||{stages:[],snags:[]},locked=!!r.handover?.approved_at;
 el.innerHTML=`<section class="mp-roadmap"><h2>Construction roadmap & quality records</h2><p>Draw → Check → Approve → Execute → Measure → Record</p><p class="mp-muted">${esc(c.notice)}</p><details><summary>Five-grade specification reference</summary><p>Structural entries are reference examples only. The selected package never sets structural sizes, concrete strength or reinforcement automatically.</p><div class="mp-scroll"><table><thead><tr><th>Specification</th>${c.grades.map(g=>`<th>${g}</th>`).join('')}</tr></thead><tbody>${c.specifications.map(s=>`<tr><th>${esc(s.item)}${s.engineer_required?'<br><small>Approved design required</small>':''}</th>${s.values.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><p>References named in supplied documents: ${esc(c.standards.join('; '))}</p></details>
 <h3>Agreed specification</h3><p>${r.grade?esc(r.grade)+' · '+(r.grade_approved?'Customer approved':'Awaiting customer approval'):'No grade agreed yet'}</p><p>${esc(r.specification||'')}</p>
 ${!locked&&contractor&&(['estimating','revision_requested'].includes(j.data.stage)||!r.grade)&&!r.stages.some(s=>s.status!=='pending')?form('grade',`<label>Material / finish grade<select name="grade">${c.grades.map(g=>`<option ${r.grade===g?'selected':''}>${g}</option>`).join('')}</select></label><label>Approved drawing revisions, actual material specifications and exclusions<textarea name="specification" required maxlength="5000">${esc(r.specification||'')}</textarea></label>`):''}
 ${!locked&&!contractor&&r.grade&&!r.grade_approved?form('approve_grade','<p>Approve the written specification above. This is client scope approval, not structural engineering certification.</p>'):''}
 <h3>Stage register</h3><p>${r.stages.filter(s=>s.status==='recorded').length} / ${r.stages.length||c.stages.length} stages recorded. Times below are planning ranges; curing periods can overlap and are not added into a project completion promise.</p>
 ${(r.stages.length?r.stages:c.stages.map(s=>({id:s.id,catalog_id:s.id,status:'pending',measurements:[],curing:[]}))).map(s=>{const spec=c.stages.find(x=>x.id===s.catalog_id);return `<details class="mp-card"><summary><strong>${esc(spec.title)}${s.floor?' · Floor '+s.floor:''}</strong> · ${esc(s.status)} ${spec.hold?' · Inspection hold point':''}</summary><p>Typical work: ${esc(spec.duration)}<br>Curing / waiting: ${esc(spec.curing)}</p><p><strong>Check:</strong> ${esc(spec.checks)}</p><p>Drawing: ${esc(s.drawing||'Not recorded')}<br>Inspector: ${esc(s.inspector||'Not recorded')}<br>Inspection: ${esc(s.check||'Not recorded')}</p>
 ${s.measurements.length?`<div class="mp-scroll"><table><thead><tr><th>Location / specification</th><th>Measured quantity</th><th>Dimensions (metres)</th></tr></thead><tbody>${s.measurements.map(m=>`<tr><td>${esc(m.description)}</td><td>${m.quantity} ${esc(m.unit)}</td><td>${esc(Object.entries(m.dimensions).map(([k,v])=>k+': '+v).join(', '))}</td></tr>`).join('')}</tbody></table></div>`:''}
 ${s.curing.map(log=>`<p>Curing / test: ${esc(log.start)} to ${esc(log.end)} · ${esc(log.instructions)}</p>`).join('')}<p>${esc(s.completion||'')}</p>
 ${!locked&&r.grade_approved&&j.data.stage==='in_execution'?(contractor?(s.status==='pending'?form('draw',note('Current drawing / specification revision'),s.id):s.status==='drawn'?form('check',field('inspector','Responsible engineer / inspector')+note('Inspection findings, checks and evidence reference'),s.id):s.status==='approved'?form('execute','<p>Record that this approved work has been executed. Earlier work and relevant curing/test gates must be satisfied.</p>',s.id):s.status==='executed'?form('measure',note('Measurement location, material grade, reinforcement details or finish specification')+`<label>Unit<select name="unit">${['m3','m2','m','kg','tonne','point','circuit','item'].map(u=>`<option>${u}</option>`).join('')}</select></label><div class="mp-grid">${field('length','Length (m)','number','step="any" min="0.001" value="1"')}${field('width','Width (m)','number','step="any" min="0.001" value="1"')}${field('depth','Depth / thickness (m), volume only','number','step="any" min="0.001" value="0.1"')}${field('count','Count','number','min="1" value="1"')}${field('quantity','Quantity for units other than m²/m³','number','step="any" min="0.001" value="1"')}</div><p>m³ = length × width × thickness × count. m² = length × width × count. Steel quantities use the approved bar schedule; no automatic reinforcement design.</p>`,s.id)+form('curing',field('start','Curing / waiting start','date')+field('end','Required end date','date')+note('Engineer / manufacturer instructions, curing observations or required test evidence'),s.id)+form('record',note('Completion evidence and responsible engineer clearance; include tests, prop removal and loading clearance as applicable'),s.id):''):s.status==='checked'?form('approve','<p>Confirm the inspection record above has been reviewed. Client approval does not replace professional engineering sign-off.</p>',s.id):''):''}</details>`;}).join('')}
 <h3>Snag register</h3>${r.snags.map(s=>`<article class="mp-card"><p>${esc(s.description)} · ${esc(s.status)}<br>Responsible: ${esc(s.responsible)} · Due: ${esc(s.due)}<br>${esc(s.resolution||'')}</p>${!locked&&contractor&&s.status==='open'?form('resolve_snag',`<input type="hidden" name="snag_id" value="${s.id}">`+note('Correction and evidence reference')):!locked&&!contractor&&s.status==='review'?form('close_snag',`<input type="hidden" name="snag_id" value="${s.id}"><p>Confirm this correction is complete.</p>`):''}</article>`).join('')||'<p>No snags recorded.</p>'}
 ${!locked&&r.grade_approved&&j.data.stage==='in_execution'?form('snag',field('description','Room / defect')+field('responsible','Responsible person')+field('due','Target correction date','date')):''}
 <h3>Final handover</h3><p>${esc(r.handover?.documents||'Final measurements, test reports, warranties, manuals, keys and as-built references must be recorded.')}</p>${locked?`<p class="mp-badge">Handover signed off ${esc(r.handover.approved_at)}</p>`:contractor&&r.grade_approved?form('handover','<label>Handover document references and final scope confirmation<textarea name="documents" maxlength="6000" required></textarea></label>'):r.handover?form('approve_handover','<p>Confirm the agreed work, records and snag corrections are complete before final sign-off.</p>'):''}</section>`;
 el.querySelectorAll('[data-roadmap-action]').forEach(f=>f.addEventListener('submit',async e=>{e.preventDefault();const button=f.querySelector('button');button.disabled=true;try{await action('roadmap',{...Object.fromEntries(new FormData(f)),operation:f.dataset.roadmapAction,stage_id:f.dataset.stage});}catch(error){let msg=f.querySelector('[role=alert]');if(!msg){msg=document.createElement('p');msg.setAttribute('role','alert');msg.className='mp-error';f.append(msg);}msg.textContent=error.message;button.disabled=false;}}));
}
root.RoadmapUI={render};
})(window);
