apiVersion: v1
kind: ServiceAccount
metadata:
  name: ohisee-backend
  labels:
    app.kubernetes.io/name: ohisee-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ohisee-frontend
  labels:
    app.kubernetes.io/name: ohisee-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ohisee-design3d-worker
  labels:
    app.kubernetes.io/name: ohisee-design3d-worker
