apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ohisee-staging

resources:
  - ../../base

patches:
  - path: patches/namespace.yaml
  - path: patches/configmap.yaml
  - path: patches/ingress.yaml
